<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_rukoProduk</name>
   <tag></tag>
   <elementGuidId>493d57f2-c119-4da4-bec6-4321224ff3f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#top-undefined</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='top-undefined']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>606d6a0c-a8ee-4191-a861-27d831d73842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TopNavMenu_nav__item__7_UVv</value>
      <webElementGuid>21fb23cb-1a5f-4a80-b08e-723828c02880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>top-undefined</value>
      <webElementGuid>74c43924-6ec1-45d2-ac83-6659ba929b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>rukoProduk</value>
      <webElementGuid>cd5c9f7f-2c1c-40aa-9b13-57bb51e34561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/header[@class=&quot;Header_header__gtmFw&quot;]/div[@class=&quot;Header_header-container__uCYa7&quot;]/div[@class=&quot;Header_header__navigation__XOeTB&quot;]/div[@class=&quot;d-none d-xl-block&quot;]/div[@class=&quot;TopNavMenu_nav__SYv5Q&quot;]/a[2]/div[@id=&quot;top-undefined&quot;]</value>
      <webElementGuid>108c7c56-34ca-4592-9007-0b53042d78c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='top-undefined']</value>
      <webElementGuid>2111ea2b-d0c9-40e1-883d-4abc748f54f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/header/div/div[2]/div[2]/div/a[2]/div</value>
      <webElementGuid>166a8e31-e50a-4532-95f7-44f9f6d77f60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beranda'])[2]/following::div[1]</value>
      <webElementGuid>f4aea46d-52ba-43a2-8454-632a7b5503e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Akun'])[1]/following::div[6]</value>
      <webElementGuid>a9fdd119-addb-43b4-98b0-963de66b2704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Akun'])[2]/preceding::div[4]</value>
      <webElementGuid>4eeee8c4-20e9-47f7-8325-55d310714039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/div</value>
      <webElementGuid>2c59d621-3ed0-4761-a28a-f34a2e48a489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'top-undefined' and (text() = 'rukoProduk' or . = 'rukoProduk')]</value>
      <webElementGuid>c1cfe95f-0a61-4e1e-a1de-ae8fc99ea33a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
