<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Beranda</name>
   <tag></tag>
   <elementGuidId>c5475532-e2ba-4dc5-95c6-80e68d685fcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.TopNavMenu_nav__item-title__YTRut</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='top-beranda-logo']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0ea5395c-f9eb-4f43-a398-24e2e46d81f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TopNavMenu_nav__item-title__YTRut</value>
      <webElementGuid>c88fefc9-1d35-435e-9ddd-c81a76b7f448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Beranda</value>
      <webElementGuid>062852f6-136d-4f46-bed6-e9c1614b7a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-beranda-logo&quot;)/div[@class=&quot;TopNavMenu_nav__item-title__YTRut&quot;]</value>
      <webElementGuid>509f65a2-9a6d-47c0-9d7c-dd7b416ee95f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top-beranda-logo']/div[2]</value>
      <webElementGuid>16d22e7c-b09e-4fe3-bcb3-b4579138ab42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Akun'])[1]/following::div[5]</value>
      <webElementGuid>90cbb449-aae8-4271-87ab-2c2d12df2cc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produk'])[1]/following::div[9]</value>
      <webElementGuid>a83ce3c8-f997-4344-aab8-f63bf317b217</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produk'])[2]/preceding::div[2]</value>
      <webElementGuid>5fce57f0-4117-4dd4-bb94-a5f64050bb42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Akun'])[2]/preceding::div[5]</value>
      <webElementGuid>ec18694d-067a-4810-805b-a68f8cba654e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div[2]</value>
      <webElementGuid>8d57212a-6208-401c-b089-e681300163be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Beranda' or . = 'Beranda')]</value>
      <webElementGuid>ec8378d7-61d3-4edb-bffb-3105f02d2b63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
