<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_user-circleAkun</name>
   <tag></tag>
   <elementGuidId>162d11c2-b3b4-433b-9645-94a78ca6d797</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(3) > #top-undefined</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='top-undefined'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4c9a5694-0d85-4dc6-9d00-f9b093750674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TopNavMenu_nav__item__7_UVv</value>
      <webElementGuid>f0234352-af25-4085-ad6d-c814f9e3df6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>top-undefined</value>
      <webElementGuid>42eabe92-01a2-4580-8e40-d937b4ae4865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>user-circleAkun</value>
      <webElementGuid>c60aae9e-4e17-400d-ba78-1629026a0cf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/header[@class=&quot;Header_header__gtmFw&quot;]/div[@class=&quot;Header_header-container__uCYa7&quot;]/div[@class=&quot;Header_header__navigation__XOeTB&quot;]/div[@class=&quot;d-none d-xl-block&quot;]/div[@class=&quot;TopNavMenu_nav__SYv5Q&quot;]/a[3]/div[@id=&quot;top-undefined&quot;]</value>
      <webElementGuid>93644599-f918-4733-bd1e-9c0ff35395c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='top-undefined'])[2]</value>
      <webElementGuid>23bdb19a-4796-4567-a723-78f912af809a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/header/div/div[2]/div[2]/div/a[3]/div</value>
      <webElementGuid>9100121b-4ac9-45bb-88bb-62ebb6b8e056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produk'])[2]/following::div[1]</value>
      <webElementGuid>387a68ef-27c6-4a9c-91c6-8252205046df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beranda'])[2]/following::div[4]</value>
      <webElementGuid>dc73d2d0-80b1-4c8c-b1b0-a9dc072922d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[1]/preceding::div[3]</value>
      <webElementGuid>c7749a5f-c02b-410b-9d48-d1a6fade2c39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/div</value>
      <webElementGuid>398bb81d-d566-4ece-b708-c425beb0ff6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'top-undefined' and (text() = 'user-circleAkun' or . = 'user-circleAkun')]</value>
      <webElementGuid>f1fc4c94-8bbc-46b1-9971-7baf24abd2cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
