<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Download App_Logo_wrapper__img__wVzd5</name>
   <tag></tag>
   <elementGuidId>7bd27f69-5f80-430b-8b8c-c15c648f483a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.Logo_wrapper__img__wVzd5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/header/div/div/a/div/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0c82f017-7576-434e-964c-5b776b01a0bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>cermati.com</value>
      <webElementGuid>11e2dae4-15e1-4dff-b71c-720bd26cbd01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Logo_wrapper__img__wVzd5</value>
      <webElementGuid>1d5a233e-7aa4-4389-8046-1109d238fbae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>2281f505-ab3e-402b-b57f-17c12b89c4bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://next-static.cermati.com/marketplace/static/images/logo/cermati-white.png</value>
      <webElementGuid>01f41217-71f1-4339-9444-5559bcf3464e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>107</value>
      <webElementGuid>7e00a6ea-a585-4dd2-8989-f50aeeffc8c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/header[@class=&quot;Header_header__gtmFw&quot;]/div[@class=&quot;Header_header-container__uCYa7&quot;]/div[@class=&quot;Header_header__logo__CZRXo&quot;]/a[1]/div[@class=&quot;Logo_wrapper__au2M_&quot;]/picture[1]/img[@class=&quot;Logo_wrapper__img__wVzd5&quot;]</value>
      <webElementGuid>9d7ed17f-6a3c-4ed7-aff3-2e42111e7196</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/header/div/div/a/div/picture/img</value>
      <webElementGuid>3cb80323-9042-4d98-9515-ad57dccdd9bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='cermati.com']</value>
      <webElementGuid>aaebb0de-e09e-4403-aa48-15f9b29f0385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>f167e74f-39a6-49e3-9fb4-16a6268e91e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'cermati.com' and @src = 'https://next-static.cermati.com/marketplace/static/images/logo/cermati-white.png']</value>
      <webElementGuid>3496e18a-c8d1-4e5f-a50e-d3ed5a41fa73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
